apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: testsite
  namespace: sites
spec:
  interval: 15m
  chart:
    spec:
      chart: grav
      version: 13.5.12
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      config:
        enabled: true
        mountPath: "/config"
      varrun:
        enabled: true
    ingress:
        main:
          enabled: true
          ingressClassName: external
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: ${TESTSITE_DNS_PREFIX}${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix


