apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: plex
    namespace: media
spec:
    interval: 15m
    chart:
        spec:
            chart: plex
            version: 20.4.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: plex
    values:
        credentials:
            cloudflare:
                accessKey: ${VOLSYNC_ACCESS_KEY}
                bucket: ${VOLSYNC_BUCKET_NAME}
                encrKey: ${PLEX_CONFIG_ENCRYPTION_KEY}
                name: cloudflare
                path: ""
                secretKey: ${VOLSYNC_SECRET_KEY}
                type: s3
                url: ${VOLSYNC_S3_URL}
        ingress:
            main:
                enabled: false
        persistence:
            config:
                enabled: true
                mountPath: /config
                size: 256Gi
                volsync:
                    - credentials: cloudflare
                      dest:
                        enabled: false
                      name: plex-config-2025
                      src:
                        enabled: true
                      type: restic
            transcode:
                enabled: true
                medium: Memory
                mountPath: /transcode
                targetSelectAll: true
                type: emptyDir
            media:
                enabled: true
                mountPath: /media
                type: nfs
                path: ${MEDIA_PATH}
                server: ${TRUENAS_IP}
        plex:
            additionalAdvertiseURL: "https://192.168.1.160:32400"
            disableGDM: true
            requireHTTPS: false
            serverIP: ${PLEX_IP}
        release_name: plex
        service:
            main:
                enabled: true
                loadBalancerIP: ${PLEX_IP}
                type: LoadBalancer
                externalTrafficPolicy: Local
                ports:
                    main:
                        port: 32400
                        protocol: http
                        targetPort: 32400
                integrations:
                    metallb:
                        enabled: true
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                ALLOWED_NETWORKS: 172.16.0.0/12,10.0.0.0/8,192.168.1.0/24
                                PLEX_CLAIM: ${PLEX_CLAIM_TOKEN}
