apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: readarr
  namespace: readarr
spec:
  interval: 5m
  chart:
    spec:
      chart: readarr
      version: 25.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: 10m
    global:
      stopAll: false
    credentials:
      cloudflare:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: ${VOLSYNC_BUCKET_NAME}
        encrKey: ${READARR_CONFIG_ENCRYPTION_KEY}
        name: cloudflare
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_S3_URL}
    ingress:
      main:
        enabled: true
        hosts:
          - host: ${RADARR_DNS_PREFIX}${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        ingressClassName: external
        integrations:
          nginx:
            enabled: true
            auth:
              type: authelia
              internalHost: authelia.authelia.svc.cluster.local:9091
              externalHost: ${AUTHELIA_DNS_PREFIX}${DOMAIN_0}
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: cloudflare
          dest:
            enabled: false
          src:
            enabled: true
      media:
        enabled: true
        mountPath: /media
        type: nfs
        path: ${MEDIA_PATH}
        server: ${TRUENAS_IP}
    metrics:
      main:
        enabled: false